version: "3.8"

services:
  server:
    image: "ioalexander/gitmirrors-backend:latest"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - gitmirrors
    environment:
      SERVER_PORT: ${SERVER_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      ROCKET_ADDRESS: ${ROCKET_ADDRESS}
      ROCKET_ENV: ${ROCKET_ENV}
      DATABASE_URL: ${DATABASE_URL}
      CORS_URL: ${CORS_URL}

  web-client:
    image: "ioalexander/gitmirrors-frontend:latest"
    ports:
      - "${WEB_CLIENT_PORT}:${WEB_CLIENT_PORT}"
    networks:
      - gitmirrors
    environment:
      PORT: ${WEB_CLIENT_PORT}
      NUXT_PUBLIC_API_URL: ${NUXT_PUBLIC_API_URL}
      NUXT_PUBLIC_SERVER_API_URL: ${NUXT_PUBLIC_SERVER_API_URL}

  db:
    image: postgres:14.4
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - gitmirrors
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
networks:
  gitmirrors:
    driver: bridge
