[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
diesel = { version = "2.2.0", features = ["postgres", "r2d2", "chrono"] }
dotenv = "0.15.0"
serde = "1.0.219"
