FROM rust:1.87-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
  build-essential \
  bash \
  pkg-config \
  libssl-dev \
  libpq-dev \
  curl \
  git \
  openssh-client \
  ca-certificates \
  postgresql-client \
  && rm -rf /var/lib/apt/lists/*

RUN cargo install cargo-watch

RUN cargo install diesel_cli --no-default-features --features postgres

WORKDIR /usr/src/app

COPY Cargo.toml Cargo.lock ./

ENTRYPOINT ["/usr/src/app/entrypoint.dev.sh"]

